version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: accountbanksa_postgres
    environment:
      POSTGRES_DB: accountbanksa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  accountbanksa:
    container_name: AccountBankSA
    restart: always
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/accountbanksa_db
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: 123456
    ports:
      - '8083:8080'
    depends_on:
    - postgres

volumes:
  postgres_data:
